# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-14 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='abstract',
            field=models.TextField(default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='Email Adress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='file_submission',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='monthly_talk',
            field=models.BooleanField(default='', max_length=50, verbose_name='Interest in monthly talk?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='outcomes',
            field=models.TextField(default='', max_length=250, verbose_name='Learning Outcomes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='prior_talks',
            field=models.URLField(blank=True, max_length=50, verbose_name='Links to previous talks'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='profile_link',
            field=models.URLField(blank=True, max_length=50, verbose_name='GitHub/Home Page'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='speaker_bio',
            field=models.TextField(default='', max_length=500, verbose_name='Speaker Bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='talk_history',
            field=models.TextField(default='', max_length=250, verbose_name='Speaker and Talk History'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='talk_title',
            field=models.TextField(default='', max_length=200, verbose_name='Talk Title'),
            preserve_default=False,
        ),
    ]
